### ISSUE TITLE
make

### ISSUE THREAD

**Issue by SAUCYSOUP76** [merbanan/rfid_app#13]
gcc -o idrw_linux idrw_linux.c -I/usr/local/include -L. -lm -lc -L/usr/local/lib -lusb-1.0
idrw_linux.c:181:10: fatal error: libusb-1.0/libusb.h: No such file or directory
 #include <libusb-1.0/libusb.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7: idrw_linux] Error 1

**Comment by merbanan** [comment]
libusb is a requirement for compilation. Make sure you install it.

**Comment by SAUCYSOUP76** [comment]
It is installed, why did you close it?

**Comment by merbanan** [comment]
You need the development package installed also (libusb-1.0-0-dev in ubuntu/debian). I close tickets when I think the issue is answered to.
