### ISSUE TITLE
Unknown or no device found:�fPh	)

### ISSUE THREAD

**Issue by Freddy789** [merbanan/rfid_app#19]
When i run the app normally like ./rfid_app -l I recieve this Error: Error while opening /dev/ttyUSB0

When i use the command as such ./rfid_app -d /dev/bus/usb/_<bus_id>_/_<device_id_> -l as suggested here https://github.com/merbanan/rfid_app/issues/3#issuecomment-325515951
I get this error Unknown or no device found:�fPh	)
I am using [this Reader](https://www.amazon.de/Zerone-Kartenleser-kontaktlosen-Proximity-Duplizierer-default/dp/B07FP6L5X7/ref=sr_1_8?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=rfid+reader&qid=1561621851&s=gateway&sr=8-8)
I would appreciate any help

**Comment by merbanan** [comment]
Can I get a copy of the software and a usbinfo -v for the device?

**Comment by Freddy789** [comment]
`pi@raspberrypi:~/Downloads/MFRC522-python $ lsusb -v

Bus 001 Device 005: ID 6688:6850  
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x6688 
  idProduct          0x6850 
  bcdDevice            1.01
  iManufacturer           1 CTX
  iProduct                2 203-ID-RW
  iSerial                 3 (error)
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              200mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      46
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0030  1x 48 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0018  1x 24 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
`

[English.zip](https://github.com/merbanan/rfid_app/files/3358173/English.zip)

Thats the English Version of what i got.. the Chinese Version is the exact same just in Chinese also thats all those 2 files no manual nothing cant even find a website of the Company

**Comment by merbanan** [comment]
Try this command not rfid_app

ctx-idrw-203

**Comment by Freddy789** [comment]
When im running that command nothing happens 
Ive tried ./ctx-idrw-203 no response in console
./ctx-idrw-203 -l no response in console
./ctx-idrw-203 -d /dev/bus/usb/001/007 -l this gives ./ctx-idrw-203: invalid option -- 'd'

**Comment by merbanan** [comment]
Just try with -b

**Comment by Freddy789** [comment]
Finally working ^^ thank you for this tool took me ages to get this reader to work

For anyone else with a simular problem type
./ctx-idrw-203 -d /dev/bus/usb/<bus_id>/<device_id> and you will get a beep from the reader 
./ctx-idrw-203 -r /dev/bus/usb/<bus_id>/<device_id> will put the reader in reading mode and read a tag/card and print its id 

Edit: It actually just works with just ./ctx-idrw-203 -r
