### ISSUE TITLE
Not able to write EM4305

### ISSUE THREAD

**Issue by exander77** [merbanan/rfid_app#2]
I am not able to write (and maybe read) EM4305, T5577 works fine.

```
./idrw_linux -f 0 -w 0F00223C29
OK
./idrw_linux -f 2 -w 0F00223C29
NOTAG
./idrw_linux -r
NOTAG
```

Bought them on Aliexpress: https://www.aliexpress.com/item/125Khz-Writable-EM4305-RFID-Key-Tags-Keyfobs-Token-Keychain-for-access-control/32518132894.html?spm=2114.13010608.0.0.2KwFKo&aff_platform=aaf&sk=zj6qB6AIM%3A&cpt=1479413738646&af=1000055000000000242022015&cn=aliexpress&cv=banner&dp=19TZ1JPLYeZA02t&tp2=4ren&&aff_trace_key=8f1ead0c6fd44fbdb628e9cd7e63424d-1479413738646-07247-zj6qB6AIM

**Comment by merbanan** [comment]
Can you test and see if they work with the windows software ?

**Comment by exander77** [comment]
I could, but I can't find CD reader anywhere. Do you know if the software is avaiable online?

**Comment by merbanan** [comment]
https://drive.google.com/file/d/0B7StsLVdpBgfaHVOLWx5Rzd2alE/view?usp=sharing

**Comment by exander77** [comment]
Don't seem to work at all for me, I can't even read T5577 on Windows. Does it need some kind of CP210x driver?

**Comment by merbanan** [comment]
No, it's a hid device, works without any drivers. Just special hid commands and payload. You should try to run the original windows software from your cd. They might have changed something in the payload structure data. Or more likely your hardware is broken.

**Comment by exander77** [comment]
No go so far, but I think it is Windows 10 related problem, gonna try Windows XP.

**Comment by exander77** [comment]
Windows XP it works, but only for T5577, so maybe the reader is broken and does not read/write EM4305.

**Comment by merbanan** [comment]
Ok, well then the software and hardware works as well as it works under Windows XP. Nothing more to do. One last thing is try to move the reader away from metal and move the tags around in the reader area. I had that issue one time with one of my readers.

**Comment by exander77** [comment]
Yes, software behaves exactly the same way on both Linux and Windows. Already encoutered that issue with bad reception, but I have tried numerous positions of the tags on the reader. I am going to contact reader/writer seller. I will inform about the results. It may be interesting to other people.

Thank you very much for your help.
