### ISSUE TITLE
Problem with my reader/writer

### ISSUE THREAD

**Issue by clemenlg** [merbanan/rfid_app#5]
Hi,
I've a chinese reader/writer, and I'm trying to use this software.
My reader is different (because vendor and idproduct are distinct):
``  looking at device '/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6':
    KERNEL=="2-1.6"
    SUBSYSTEM=="usb"
    DRIVER=="usb"
    ATTR{authorized}=="1"
    ATTR{avoid_reset_quirk}=="0"
    ATTR{bConfigurationValue}=="1"
    ATTR{bDeviceClass}=="00"
    ATTR{bDeviceProtocol}=="00"
    ATTR{bDeviceSubClass}=="00"
    ATTR{bMaxPacketSize0}=="64"
    ATTR{bMaxPower}=="100mA"
    ATTR{bNumConfigurations}=="1"
    ATTR{bNumInterfaces}==" 1"
    ATTR{bcdDevice}=="0100"
    ATTR{bmAttributes}=="80"
    ATTR{busnum}=="2"
    ATTR{configuration}==""
    ATTR{devnum}=="7"
    ATTR{devpath}=="1.6"
    ATTR{idProduct}=="ea60"
    ATTR{idVendor}=="10c4"
    ATTR{ltm_capable}=="no"
    ATTR{manufacturer}=="Silicon Labs"
    ATTR{maxchild}=="0"
    ATTR{product}=="CP2102 USB to UART Bridge Controller"
    ATTR{quirks}=="0x0"
    ATTR{removable}=="removable"
    ATTR{serial}=="0001"
    ATTR{speed}=="12"
    ATTR{urbnum}=="24"
    ATTR{version}==" 1.10"``
I add a new rule in 20-rwrfid.rules:
``ATTR{idVendor}=="10c4", ATTR{idProduct}=="ea60", MODE="664", GROUP="plugdev"``
But I can't find the device with "rfid_app -l". get_id function returns device empty.
Can you help me to try to find my device?
Regards

**Comment by merbanan** [comment]
You need to send me a copy of the windows software.

**Comment by merbanan** [comment]
Modification of 20-rwrfid.rules is not needed. You need permissions to the serial port. Try running with super user permissions.

**Comment by clemenlg** [comment]
Hi,
This is the link for the software: https://wetransfer.com/downloads/59a525d62365be1a015aebf610a3c3f920180211101712/5e826fcf39e2ed856d293d651472224420180211101712/57d492
I tried to run it as root.
I changed the udev rules because vendor and productid is different.
Regards

**Comment by merbanan** [comment]
Hi, this device uses an unsupported protocol. It will not work with rfid_app. Where did you buy this reader ?

**Comment by clemenlg** [comment]
I bought it in aliexpress (https://es.aliexpress.com/item/RFID-EM4305-reader-and-writer-125-134-2KHZ-ISO-11784-85-card-reader-animal-chip-write/32825350730.html?spm=a2g0s.9042311.0.0.Rdw2M0). It's simply a rfid writer for FDX-B chips.

**Comment by clemenlg** [comment]
I close this issue, because it's not really a issue.
