### ISSUE TITLE
Format of the Read/Write Operations?

### ISSUE THREAD

**Issue by maxieds** [merbanan/rfid_app#6]
Hello. I couldn't find your contact email on the site or in the README, so I guess I'll ask this here. 

Can you provide more detailed information about how you found the read/write formats for the SYC device? I'm interested in what else one can do with these devices. For reference, I have one of [these](https://www.amazon.com/dp/B016RRQQIY/?tag=stackoverflow17-20) USB RFID readers. I'd like to be able to sniff more about what's getting detected by the hardware in the device and am curious as to what other hidden features may be available. Any help with this is appreciated.

**Comment by merbanan** [comment]
Hi, there is a windows application that can set these parameters. I looked at the usb traffic to figure out the protocol. The software had no more switches to toggle then what this tool has support for. But if you look at the protocol description in the source you see that there isn't so much more that could hold feature toggles.

11-13   00                      <- unknown always the same

These are the best candidates for tinkering. Happy hacking. And my email is in the source code.

**Comment by maxieds** [comment]
Do you have any suggestions for getting the hardware to sniff intermittent
bits of the 125kHz protocol? Sort of like the Chameleon boards can do for
the 13*mHz channels?

**Comment by merbanan** [comment]
Any FX2 logic analyzer board should do. My favorite hardware is the LHT00SU1 hardware found on ebay. But a $6 usb logic analyzer from ebay will work fine also. If you use sigrok there are protocol decoders available also:  https://sigrok.org/blog/new-protocol-decoder-em4100
