### ISSUE TITLE
Speed up read times?

### ISSUE THREAD

**Issue by scottlee** [merbanan/rfid_app#9]
Is it possible to speed up the read times? I'm looking to run the rfid_app in a loop via Bash and I've noticed that there's quite a bit of delay while trying to read a card.

Thanks for this app, btw! It's the only way I've been able to successfully use my RFID reader.

**Comment by merbanan** [comment]
Hi, change sleep(1) to something lower usleep(500) or something else.

https://github.com/merbanan/rfid_app/blob/master/rfid_app.c#L120

**Comment by scottlee** [comment]
Very cool. Thanks again, @merbanan.

**Comment by merbanan** [comment]
For some good karma report back what values are fine for you.
